server:
  port: 8080
spring:
  r2dbc:
    url: "r2dbc:postgresql://evoxprodb01.culzj05sqpfp.us-east-2.rds.amazonaws.com"
    username: "postgres"
    password: "pv08UiLi11T76tbs$%qpvb1"
  application:
    name: evox
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
  expiration : 3600
evox:
  url: "https://evox/ref/"
  email:
    sender: "corporate@evox.com.co"
    password : "Evoteam2022"

logging:
  level:
    org:
      springframework:
        web:
          cors:
            reactive:
              DefaultCorsProcessor: debug
