server:
  port: 8080
spring:
  r2dbc:
    url: "r2dbc:postgresql://3.140.1.248:5432/evox-prod"
    username: "postgres"
    password: "evoxproduccion"
  #r2dbc:
   # url: r2dbc:postgresql://${rds.db.url}
   # username: ${rds.db.username}
   # password: ${rds.db.password}
  application:
    name: evox
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
  expiration : 3600
evox:
  url: "https://www.backoffice.evox.com.co/"
  email:
    sender: "corporate@evox.com.co"
    password : "Evoteam2022"
