spring:
  r2dbc:
    url: "r2dbc:postgresql://3.140.1.248:5432/evox-prod"
    username: "postgres"
    password: "evoxproduccion"
  application:
    name: evox
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
  expiration : 3600
evox:
  url: "https://www.backoffice.evox.com.co/"
  email:
    sender: "corporate@evox.com.co"
    password : "Evoteam2022"
