spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/eboxdb"
    username: "postgres"
    password: "postgres"
    # url: r2dbc:postgresql://${URL_DATABASE}
    # username: ${USERNAME}
    # password: ${PASSWORD}
  application:
    name: evox
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
  expiration : 3600
evox:
  url: https://backoffice.evox.com.co/
  email:
    sender: corporate@evox.com.co
    password: Evoteam2022
    #password : ${PASSWORD_EMAIL}
